### ISSUE TITLE
Configuration file parse error: unrecognized line in ' '

### ISSUE THREAD

**Issue by PabloIriso** [skodapetr/autodock-vina#2]
After executing

     vina --config conf.txt --log logVenlafaxine.txt

I 'm  getting the error:

    Configuration file parse error: unrecognized line in ' '

Apparently, Vina is not able to connect the files. However, this is my conf.txt file:

_receptor= S1S2_02_c.pdbqt
ligand= venlafaxine3D_CID_5656.pdbqt
 
center_x= 4.749
center_y= -11.371
center_z= -45.264
  
size_x= 54
size_y= 48
size_z= 42
  
out= vina_outVenlafaxine.pdbqt
log= logVenlafaxine.txt 
 
exhaustiveness= 8_

And these are my pdbqt files in the same folder as _conf.txt_

    venlafaxine3D_CID_5656.pdbqt

    S1S2_02_c.pdbqt

However, if I parse the args in the command line it executes well:

     vina --receptor S1S2_02_c.pdbqt --ligand venlafaxine3D_CID_5656.pdbqt --center_x 4.749 --center_y -11.371 --center_z      -45.264 --size_x 54 --size_y 48 --size_z 42 --out vina_outVenlafaxine.pdbqt --log logVenlafaxine.txt

**Comment by skodapetr** [comment]
Sorry for the delay.

@PabloIriso : It seems that the issue is in the configuration file, on the empty lines you have UTF character for non-breakable space (c2a0) which cause boost function ```parse_config_file``` to fail.  The fastest solution is to remove those characters from the configuration file. 

An alternative would be to create an issue to Boost Library.  I've tried with the with boost 1.76 and I still got the same error.
